dataset_name: ADHD200
image_path: ./data/ADHD200_MNI_to_TRs_minmax
image_path_fc: ./data/HCP1200_MNI_to_TRs_minmax

tasks:
  task3:
    downstream_task_id: 3
    task_name: diagnosis
    downstream_task_type: classification
    num_classes: 2

defaults:
  split_root: ./nas/splits
  dataset_split_num: 1
  limit_training_samples: 1.0
  batch_size_override: 2
