dataset_name: HCP1200
image_path: /data/cwang/remote/fmri/hcpya_preprocessed
image_path_fc: /data/cwang/remote/fmri/hcpya_preprocessed

tasks:
  task1:
    downstream_task_id: 1
    task_name: sex
    downstream_task_type: classification
    num_classes: 2
  task1_age:
    downstream_task_id: 1
    task_name: age
    downstream_task_type: regression
    num_classes: 1
  task2:
    downstream_task_id: 2
    task_name: MMSE_Score
    downstream_task_type: regression
    num_classes: 1

defaults:
  dataset_split_num: 1
  limit_training_samples: 1.0
