dataset_name: HCPA
image_path: /data_ssd/cwang/fmri/hcpa_processed
image_path_fc: /data_ssd/cwang/fmri/hcpa_processed

pretrain_only: true

defaults:
  split_root: ./nas/splits
  dataset_split_num: 1
  batch_size_override: 8
