dataset_name: MOVIE
image_path: ./data/MOVIE_preprocessed
image_path_fc: ./data/HCP1200_MNI_to_TRs_minmax

tasks:
  task5:
    downstream_task_id: 5
    task_name: movie_classification
    downstream_task_type: classification
    num_classes: 5

defaults:
  split_root: ./nas/splits
  dataset_split_num: 1
  limit_training_samples: 1.0
